language: node_js
node_js:
  - 16

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # prints the version of docker for logging
  - docker build -t reverseproxy ./udagram-deployment/reverseproxy # verify correct
  - docker tag reverseproxy cort0619/reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend # verify this is ok
  - docker tag udagram-frontend cort0619/udagram-frontend
  - docker build -t udagram-feeds-api ./udagram-feeds-api # verify this is ok
  - docker tag udagram-feeds-api cort0619/udagram-feeds-api
  - docker build -t udagram-user-api ./udagram-user-api # verify this is ok
  - docker tag udagram-user-api cort0619/udagram-user-api

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cort0619/reverseproxy
  - docker push cort0619/udagram-frontend
  - docker push cort0619/udagram-user-api
  - docker push cort0619/udagram-feeds-api
