apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend # app may need to be service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend # app may need to be service
      api: external
  template:
    metadata:
      labels:
        api: external
        service: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: cort0619/udagram-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always