apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend # app may need to be service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend # app may need to be service
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: cort0619/udagram-frontend
        ports:
        - containerPort: 80